### ISSUE TITLE
Publish to custom thunderstore team

### ISSUE THREAD

**Issue by legoandmars** [MaxWasUnavailable/LobbyCompatibility#3]
Ideally this package will be on a custom thunderstore team made for this plugin ("LobbyLobbers" or something, idk)

Unless max is open to giving future maintainers/collaborators access to his personal thunderstore team (or LethalAPI's thunderstore team, if that's where it's published)

**Comment by Xilophor** [comment]
The Thunderstore team is set up (BMX)
