### ISSUE TITLE
Log lobby diff data and hash in an accessible way

### ISSUE THREAD

**Issue by legoandmars** [MaxWasUnavailable/LobbyCompatibility#31]
If somebody needs mod support, it would be very useful to have:
- Their mod hash
- A list of their mods (bepinex should provide this, although maybe we could print an additional string if we feel it's necessary)
- The mod hash/modlist of somebody they're trying to join, *especially* if it fails
Ideally we should be logging all of this

**Comment by Xilophor** [comment]
I believe the BepInEx version on Thunderstore has the Logging.Disk set to log all, so we *should* be able to LogDebug the info and it will appear in the logs.
