### ISSUE TITLE
[Issue] will block vanilla error message dialog

### ISSUE THREAD

**Issue by CoolLKKPS** [MaxWasUnavailable/LobbyCompatibility#61]
same as topic, hope can fix as soon as possible, this mod is pretty good actually

**Comment by CoolLKKPS** [comment]
@Xilophor

**Comment by Xilophor** [comment]
Can you give an example, or be more explicit in what the issue is?

**Comment by CoolLKKPS** [comment]
@Xilophor ok i hope u still online bc i will send logs for u

**Comment by CoolLKKPS** [comment]
[LogOutput.log](https://github.com/MaxWasUnavailable/LobbyCompatibility/files/14675981/LogOutput.log)
delete after u see it

**Comment by CoolLKKPS** [comment]
> [Warning:Better Lobbies] 21, 0
> [Warning:Better Lobbies] True
> [Warning:Better Lobbies] 0
> This mean the user are disconnected no matter the reason

for example, such like "The host has disconnected" or "An error occurred" vanilla error dialog should display, and there has many different error dialog type, but will no longer display after install this mod, those message are real important
ok u might think join error are not important, but sometime the host will send message though the error dialog

**Comment by CoolLKKPS** [comment]
u can just unblock the vanilla dialog, as long as LobbyCompatibility dialog can be display

**Comment by CoolLKKPS** [comment]
changed something

**Comment by Xilophor** [comment]
> > [Warning:Better Lobbies] 21, 0
> > [Warning:Better Lobbies] True
> > [Warning:Better Lobbies] 0
> > This mean the user are disconnected from lobby for some reason
> 
> for example, such like "The host has disconnected" or "An error occurred" vanilla error dialog should display, and there has many different error dialog type, but will no longer display after install this mod, those message are real important ok u might think join error are not important, but sometime the host will send message though the error dialog if im right

Just to confirm, errors outside of an error when joining w/ incompatibilities does not display?

**Comment by CoolLKKPS** [comment]
@Xilophor LobbyCompatibility error dialog can display but vanilla error dialog cannot, that's all i can confirm

**Comment by CoolLKKPS** [comment]
ok bc vanilla error dialog are really important, so can't wait the fixes are come, i might need to think about uninstall to deal with temporary sorry...

**Comment by MaxWasUnavailable** [comment]
This moreso seems like a compatibility issue / compatibility request with "Better Lobbies"?

We can look into adding the LobbyIncompatibility dialogue to after vanilla's, though it might be more complicated than we can sort out in a quick hotfix.

**Comment by CoolLKKPS** [comment]
@Xilophor @MaxWasUnavailable idk is this a compatibility issue or not, but im testing rn
and can u guys pls, Don't add any prefix in my lobby name, i really hate that, vanilla compatibility lobby but force add [MOD] prefix! that prefix are really stoping me back from testing mods
