### ISSUE TITLE
[Issue] Unknown check passing on Registered Mods

### ISSUE THREAD

**Issue by Xilophor** [MaxWasUnavailable/LobbyCompatibility#62]
The unknown mod check is passing for mods that are registered through the available register method. This causes the mod to be displayed as both Compatible/Incompatible & Unknown.

![image](https://github.com/MaxWasUnavailable/LobbyCompatibility/assets/26671040/b9f646d8-b5a7-4c64-8bd9-27e5437a54b2)

![image](https://github.com/MaxWasUnavailable/LobbyCompatibility/assets/26671040/66b69c02-7e93-4c00-a788-a9e79f52ec2d)

**Comment by MaxWasUnavailable** [comment]
Very likely because we only check attributed assemblies with our unknowns, right now.

**Comment by MaxWasUnavailable** [comment]
Should be an easy fix. I'll have a look later today / this weekend.

**Comment by MaxWasUnavailable** [comment]
Should be resolved. Needs a quick test, however.
