### ISSUE TITLE
Conflict with the Sort by Player Count mod

### ISSUE THREAD

**Issue by 1A3Dev** [MaxWasUnavailable/LobbyCompatibility#63]
When using LobbyCompatibility alongside https://thunderstore.io/c/lethal-company/p/LoadingSomething/Sort_by_Player_Count/ it shows two refresh buttons (the top one is the sort button and the bottom one is the refresh button): 
![1710988803](https://github.com/MaxWasUnavailable/LobbyCompatibility/assets/23743032/ef3a26ee-f31b-46e2-a5f8-689bb477ae99)

**Comment by Xilophor** [comment]
This isn't something we can fix on our side. The Sort mod copies & modifies the refresh button on a postfix of `MenuManager::Start`, which we postfix for our UI loading as well. We have our postfix set to a priority of `Priority.Last`, which *should* run the postfix after everything else has ran; however, it appears as this is not the case. Changing the priority to First doesn't appear to fix the issue either. 

Thus the only (likely) solution is for the Sort mod to add `[HarmonyPriority(Priority.HigherThanNormal)]` or some other priority that is not `Priority.Last`.
