### ISSUE TITLE
[Feedback] optional to remove prefix

### ISSUE THREAD

**Issue by CoolLKKPS** [MaxWasUnavailable/LobbyCompatibility#69]
same as topic

**Comment by FrostyCirno** [comment]
I am also having the same issue :(. Please remove the prefix

**Comment by CoolLKKPS** [comment]
more like some mods not set category correctly, so i convert this issue to feedback

**Comment by CoolLKKPS** [comment]
i won't continue this issue, bc i will completely ignore this
