### ISSUE TITLE
[Conflict] with Lobby Improvement (password window pop-up blocked by this mod)

### ISSUE THREAD

**Issue by CoolLKKPS** [MaxWasUnavailable/LobbyCompatibility#74]
same as topic, and really this mod block vanilla windows pop-up again, this mod pop-up should always display behind the vanilla error dialog, and `NOT BLOCK ANY OTHER DIALOG`

**Comment by 1A3Dev** [comment]
https://github.com/MaxWasUnavailable/LobbyCompatibility/pull/75
https://github.com/MaxWasUnavailable/LobbyCompatibility/pull/76

Also improved compatibility from LobbyImprovements' side so the mod mismatch stuff fully works with LAN lobbies

**Comment by MaxWasUnavailable** [comment]
Thanks for the PR, @1A3Dev !
